networks:
  default:
    name: xion-net
  mc-net:
    name: mc-net
    
volumes:
  mc-proxy-data:
    name: mc-proxy-data
  portainer-data:
    name: portainer-data
  beszel-data:
    name: beszel-data

services:
  # --- DIAGRAMS & DRAWING ---
  drawio:
    image: jgraph/drawio:29.6.6
    container_name: drawio
    restart: unless-stopped
    ports: 
      - "3001:8080/tcp"

       # --- Cloud Console ---
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "3002:9000/tcp"
 
  # --- Reccource Monitoring ---     
  beszel:
    image: henrygd/beszel:0.18.5
    container_name: beszel
    restart: unless-stopped
    ports:
      - "3003:8090/tcp" # Web UI
    volumes:
      - beszel-data:/beszel_data
    environment:
      USER: ${ENV_BESZEL_USERNAME}
      PASSWORD: ${ENV_BESZEL_PASSWORD} # Optional: set password
      
  # --- Minecraft Server ---
  minecraft-proxy:
    image: itzg/minecraft-server:${ENV_MC_IMAGE_VERSION}
    container_name: mc-server
    hostname: mc-server
    stdin_open: true
    ports:
      - "25565:25565/tcp"
    environment:
      EULA: "TRUE"
      TYPE: ${ENV_MC_TYPE}
      MEMORY: ${ENV_MC_MEMORY}
      VERSION: ${ENV_MC_VERSION}
    volumes:
      - mc-data:/data
    restart: ${ENV_MC_RESTART}


  

