networks:
  default:
    name: xion-net
  mc-net:
    name: mc-net
    
volumes:
  mc-server-data:
    name: mc-server-data
  portainer-data:
    name: portainer-data
  ollama-data:
    name: ollama-data

services:
  # --- DIAGRAMS & DRAWING ---
  drawio:
    image: jgraph/drawio:29.6.6
    container_name: drawio
    restart: unless-stopped
    ports: 
      - "3001:8080/tcp"

  # --- Cloud Console ---
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ee:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "3002:9000/tcp"

  # -- Local AI ---
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    restart: ${ENV_OLLAMA_RESTART}

  # --- Minecraft Server ---
  mc-server:
    image: itzg/minecraft-server:${ENV_MC_IMAGE_VERSION}
    container_name: mc-server
    hostname: mc-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565/tcp"
    environment:
      EULA: "TRUE"
      TYPE: ${ENV_MC_TYPE}
      MEMORY: ${ENV_MC_MEMORY}
      VERSION: ${ENV_MC_VERSION}
    volumes:
      - mc-server-data:/data
    restart: ${ENV_MC_RESTART}



  

