name: Remote Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Nutzt deinen eigenen Server statt GitHub-Server
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Docker Stack
        run: |
          # 1. Neueste Images ziehen (falls externe Registry genutzt wird)
          docker compose pull
          
          # 2. Container neu bauen und im Hintergrund starten
          # --remove-orphans löscht alte Container, die nicht mehr in der Datei stehen
          docker compose up -d --build --remove-orphans
          
          # 3. Aufräumen (optional): löscht ungenutzte Images/Layer
          docker image prune -f

